In [ ]:
# --- Imports ---
import numpy as np

# Verifica la versión instalada en tu sesión de Colab
print(np.__version__)  # anota la versión para reproducibilidad

In [ ]:
# Desde una lista de Python
precios = np.array([10.5, 20.0, 15.75, 8.3])
print(precios)        # [10.5  20.   15.75   8.3]
print(type(precios))  # <class 'numpy.ndarray'>

# Con rango numérico (como range(), pero devuelve un array)
indices = np.arange(0, 10, 2)   # de 0 a 10, paso 2
print(indices)                   # [0 2 4 6 8]

# Con valores uniformemente espaciados
umbrales = np.linspace(0, 1, 5)  # 5 puntos entre 0 y 1
print(umbrales)                  # [0.   0.25 0.5  0.75 1.  ]

In [ ]:
# Crear una matriz 2D (simulando un dataset pequeño)
# 4 ejemplos, 3 características
datos = np.array([
    [1.2, 3.4, 0.5],
    [2.1, 1.0, 4.2],
    [0.8, 2.7, 1.9],
    [3.3, 0.4, 2.6]
])

print('Forma:   ', datos.shape)   # (4, 3) → 4 filas, 3 columnas
print('Tipo:    ', datos.dtype)   # float64
print('Tamaño:  ', datos.size)    # 12  (4 × 3 elementos en total)

In [ ]:
# ❌ Python puro: bucle explícito
temp_c = [0, 20, 37, 100]
temp_f = []
for t in temp_c:
    temp_f.append(t * 9/5 + 32)

# ✅ NumPy: operación vectorizada (mismos datos, sin bucle)
temp_c = np.array([0, 20, 37, 100])
temp_f = temp_c * 9/5 + 32
print(temp_f)  # [ 32.   68.   98.6 212. ]

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)    # [11 22 33 44]  → suma elemento a elemento
print(a * b)    # [ 10  40  90 160]
print(b / a)    # [10. 10. 10. 10.]
print(a ** 2)   # [ 1  4  9 16]   → potencia de cada elemento

In [ ]:
notas = np.array([7.5, 8.2, 6.0, 9.1, 5.5, 8.8])

print('Media:     ', np.mean(notas))    # 7.516...
print('Desv. std: ', np.std(notas))     # 1.274...
print('Mínimo:    ', np.min(notas))     # 5.5
print('Máximo:    ', np.max(notas))     # 9.1
print('Suma:      ', np.sum(notas))     # 45.1
print('Mediana:   ', np.median(notas))  # 7.85

In [ ]:
# Matriz: 3 ejemplos, 2 características (altura cm, peso kg)
mediciones = np.array([
    [165, 60],
    [180, 80],
    [170, 70]
])

# axis=0 → opera sobre las filas → resultado por columna
media_col = np.mean(mediciones, axis=0)
print(media_col)  # [171.67  70.  ]

# axis=1 → opera sobre las columnas → resultado por fila
media_fil = np.mean(mediciones, axis=1)
print(media_fil)  # [112.5  130.   120. ]

In [ ]:
# Ejemplo de broadcasting válido
fila  = np.array([[1, 2, 3]])   # shape: (1, 3)
col   = np.array([[10], [20],[30]])  # shape: (3, 1)

# NumPy expande 'fila' a (3,3) y 'col' a (3,3) → resultado (3,3)
print(fila + col)
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]


# ❌ Broadcasting inválido: shapes (3,) y (2,1) no son compatibles
a = np.array([1, 2, 3])          # shape: (3,)
b = np.array([[10], [20]])       # shape: (2, 1)
# Descomentar para ver el error en vivo:
# try:
#     print(a + b)
# except ValueError as e:
#     print(f'Error esperado: {e}')

# ✅ La forma correcta: convertir a shapes compatibles
a_col = a.reshape(-1, 1)         # shape: (3, 1)
c     = np.array([[10, 20]])     # shape: (1, 2)
print(a_col + c)                 # resultado shape: (3, 2)

In [ ]:
# ⚠️ Broadcasting que funciona... pero puede sorprenderte
v1d = np.array([1, 2, 3])        # shape: (3,)
v2d = np.array([[10, 20, 30]])   # shape: (1, 3)

# Alguien esperaba (3,) o (1,3) → el resultado es (3, 3)
resultado = v1d + v2d
print(resultado.shape)           


In [ ]:
# Normalizar manualmente: restar la media y dividir por desv. std
X = np.array([
    [2.0, 400],
    [3.0, 600],
    [4.0, 500]
])  # shape: (3, 2)

media = np.mean(X, axis=0)   # shape: (2,)  → [3.0, 500.0]
std   = np.std(X, axis=0)    # shape: (2,)  → [0.816, 81.6]

In [ ]:
# Broadcasting expande 'media' y 'std' para cubrir las 3 filas
X_norm = (X - media) / std
print(X_norm)
# [[-1.22 -1.22]
#  [ 0.    0.  ]
#  [ 1.22  1.22]]

In [ ]:
media = np.mean(X, axis=0)

# Versión estándar: X_norm es un array NUEVO, X no cambia
X_norm = X - media

# Versión in-place: modifica X directamente, sin array intermedio
X -= media

# ✅ Usa la versión estándar cuando necesites conservar X original
# ✅ Usa in-place cuando X ya no lo necesitas (ahorra memoria)

In [ ]:
M = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Un solo elemento: M[fila, columna]
print(M[1, 2])     # 60

# Una fila completa
print(M[0, :])     # [10 20 30]  (la primera fila)

In [ ]:
# Una columna completa
print(M[:, 1])     # [20 50 80]  (la segunda columna)

# Submatriz: primeras 2 filas, últimas 2 columnas
print(M[:2, 1:])   # [[20 30]
                #  [50 60]]


# Generamos datos reproducibles con semilla fija
rng = np.random.default_rng(42)          # generador moderno (recomendado)
dataset = rng.standard_normal((5, 4))    # 5 ejemplos, 3 features + 1 etiqueta

# La última columna es la variable objetivo (y)
X = dataset[:, :-1]   # todas las filas, todas las columnas menos la última
y = dataset[:, -1]    # todas las filas, solo la última columna

print('dataset shape:', dataset.shape)  # (5, 4)
print('X shape:      ', X.shape)        # (5, 3)
print('y shape:      ', y.shape)        # (5,)

In [ ]:
# Mezcla int + float → se promociona a float64 (inofensivo)
arr1 = np.array([1, 2, 3.5])
print(arr1.dtype)   # float64

# Mezcla números + string → todo se convierte a objeto (peligroso)
arr2 = np.array([1, 2, '3'])
print(arr2.dtype)   # <U21 (string Unicode)
# arr2 * 2  →  ['11', '22', '33']  en lugar de [2, 4, 6]

In [ ]:
v = np.array([1, 2, 3])
col = v.reshape(-1, 1)   # shape: (3, 1) — posiblemente una vista
col[0, 0] = 99
print(v)                 # [99  2  3]  ← v también cambió

# Si necesitas independencia: usa .reshape(-1, 1).copy()
col_safe = v.reshape(-1, 1).copy()

In [ ]:
# ❌ API antigua (legacy)
np.random.seed(42)
datos = np.random.randn(5, 4)

# ✅ API moderna (recomendada)
rng   = np.random.default_rng(42)
datos = rng.standard_normal((5, 4))